In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
df = pd.read_csv("../../artifacts/data/wisata.csv")
df.head()

,kategori_wisata_id,nama_tempat,jam_buka,jam_tutup,alamat,lokasi_geo,htm_min_domestik,htm_max_domestik,htm_min_mancanegara,htm_max_mancanegara,akses_transportasi,rating
0,Wisata Alam,Waduk Tirto Agro -Glenmore,07:30:00,16:00:00,"Dusun Karanganyar, Kajarharjo, Kec. Kalibaru","-8.2788264,113.9324687",10000.0,10000.0,10000.0,10000.0,"Mobil, Sepeda Motor",0.0
1,Wisata Edukasi,Penangkaran Banteng Baluran,07:30:00,16:00:00,0,"-7.83097579646207, 114.38752901123405",21000.0,31000.0,150000.0,225000.0,"Mobil, Sepeda Motor, Bus",0.0
2,Wisata Edukasi,Kebun Kopi Kemiren,08:00:00,17:00:00,"Dusun Kedaleman, Kemiren, Kec. Glagah","-8.201449434118924, 114.32217474598616",0.0,0.0,0.0,0.0,"Mobil, Sepeda Motor",4.7
3,Wisata Budaya,Sanggar Genjah Arum,08:00:00,16:00:00,"Kemiren, Glagah, Dusun Krajan, Kemiren, Kec. B...","-8.2018766,114.298193",20000.0,450000.0,20000.0,450000.0,"mobil, sepeda motor, bus",4.8
4,Wisata Alam,Bukit Mondoleko,05:00:00,17:00:00,"Area Pesawahan, Temuguruh, Kec. Sempu","-8.235249255000987, 114.16452966653851",10000.0,10000.0,10000.0,10000.0,"Mobil, Sepeda Motor",4.0

In [11]:
# Bersihkan dan normalisasi nama kolom
df.columns = df.columns.str.replace('_', ' ').str.title()

# Mapping kolom CSV ke nama yang diharapkan
column_mapping = {
    'Kategori Wisata Id': 'Kategori',
    'Nama Tempat': 'Nama Tempat',
    'Jam Buka': 'Jam Buka',
    'Jam Tutup': 'Jam Tutup',
    'Lokasi Geo': 'GPS Location',
    'Htm Min Domestik': 'HTM Min Domestic',
    'Htm Max Domestik': 'HTM Max Domestic',
    'Htm Min Mancanegara': 'HTM Min Mancanegara',
    'Htm Max Mancanegara': 'HTM Max Mancanegara',
    'Akses Transportasi': 'Moda Transportasi',
    'Rating': 'Rating'
}

df = df.rename(columns=column_mapping)

# Pastikan rating adalah numeric
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').fillna(0)

df.head()

,Kategori,Nama Tempat,Jam Buka,Jam Tutup,Alamat,GPS Location,HTM Min Domestic,HTM Max Domestic,HTM Min Mancanegara,HTM Max Mancanegara,Moda Transportasi,Rating
0,Wisata Alam,Waduk Tirto Agro -Glenmore,07:30:00,16:00:00,"Dusun Karanganyar, Kajarharjo, Kec. Kalibaru","-8.2788264,113.9324687",10000.0,10000.0,10000.0,10000.0,"Mobil, Sepeda Motor",0.0
1,Wisata Edukasi,Penangkaran Banteng Baluran,07:30:00,16:00:00,0,"-7.83097579646207, 114.38752901123405",21000.0,31000.0,150000.0,225000.0,"Mobil, Sepeda Motor, Bus",0.0
2,Wisata Edukasi,Kebun Kopi Kemiren,08:00:00,17:00:00,"Dusun Kedaleman, Kemiren, Kec. Glagah","-8.201449434118924, 114.32217474598616",0.0,0.0,0.0,0.0,"Mobil, Sepeda Motor",4.7
3,Wisata Budaya,Sanggar Genjah Arum,08:00:00,16:00:00,"Kemiren, Glagah, Dusun Krajan, Kemiren, Kec. B...","-8.2018766,114.298193",20000.0,450000.0,20000.0,450000.0,"mobil, sepeda motor, bus",4.8
4,Wisata Alam,Bukit Mondoleko,05:00:00,17:00:00,"Area Pesawahan, Temuguruh, Kec. Sempu","-8.235249255000987, 114.16452966653851",10000.0,10000.0,10000.0,10000.0,"Mobil, Sepeda Motor",4.0

In [12]:
ratings = pd.DataFrame({
    'user_id': np.random.randint(1, 15, 80),
    'wisata': np.random.choice(df['Nama Tempat'], 80),
    'rating': np.random.randint(3, 6, 80)
})

ratings.head()

   user_id                       wisata  rating
0        9  Penangkaran Banteng Baluran       4
1        3                  Gunung Ijen       4
2       12        Pura Agung Blambangan       4
3       10                  Pantai Boom       4
4        2           Kebun Kopi Kemiren       3

In [13]:
saved = pd.DataFrame({
    'user_id': np.random.randint(1, 15, 40),
    'wisata': np.random.choice(df['Nama Tempat'], 40),
    'saved': 1
})

saved.head()

   user_id                            wisata  saved
0        3                    Pantai So Long      1
1        4  Kebun Naga dan Jeruk Pesanggaran      1
2        6        Savana Sadengan Alas Purwo      1
3       14                      Muara Mbaduk      1
4       11               Air Terjun Legomoro      1

In [14]:
interaction = pd.merge(
    ratings,
    saved,
    on=['user_id','wisata'],
    how='outer'
).fillna(0)

interaction['score'] = interaction['rating'] + interaction['saved']

interaction.head()

   user_id                      wisata  rating  saved  score
0        1         Air Terjun Legomoro     4.0    0.0    4.0
1        1                 Gunung Ijen     0.0    1.0    1.0
2        1      Kebun Kopi Gombengsari     4.0    0.0    4.0
3        1                Pantai Bedul     4.0    0.0    4.0
4        1  Penangkaran Penyu Sukomade     0.0    1.0    1.0

In [15]:
user_item_matrix = interaction.pivot_table(
    index='user_id',
    columns='wisata',
    values='rating'
).fillna(0)

user_item_matrix.head()

wisata,Air Terjun Giri Asih,Air Terjun Kedung Angin,Air Terjun Legomoro,Air Terjun Lider,Air Terjun Pertemon,Air Terjun Selendang Arum,Air Terjun Seloresi,Air Terjun Telunjuk Raung,Air Terjun Temcor,Air Terjun Tlepak (Bayu Lor),...,Waduk Sidodadi Glenmore,Waduk Tirto Agro -Glenmore,capas,doeson kakoe,kali sawah adventure,pantai gumuk kantong,pantai pancur alas purwo,sendang seruni,wisata Beji antaboga,wisata japuro
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,5.0,0.0,0.0

In [16]:
similarity = cosine_similarity(user_item_matrix)

similarity_df = pd.DataFrame(
    similarity,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)

similarity_df.head(10)

user_id,1,2,3,4,5,6,7,8,9,10,11,12,13,14
user_id,,,,,,,,,,,,,,
1,1.000000,0.000000,0.126531,0.294484,0.000000,0.143922,0.000000,0.204025,0.000000,0.139131,0.000000,0.125568,0.0,0.245951
2,0.000000,1.000000,0.000000,0.198030,0.000000,0.000000,0.000000,0.257248,0.264628,0.140340,0.321246,0.000000,0.0,0.000000
3,0.126531,0.000000,1.000000,0.000000,0.000000,0.139994,0.000000,0.396911,0.000000,0.135333,0.000000,0.274817,0.0,0.000000
4,0.294484,0.198030,0.000000,1.000000,0.000000,0.078196,0.000000,0.138564,0.142539,0.157485,0.173036,0.000000,0.0,0.178174
5,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.176483,0.000000,0.000000,0.0,0.000000
6,0.143922,0.000000,0.139994,0.078196,0.000000,1.000000,0.000000,0.225733,0.000000,0.123147,0.000000,0.138929,0.0,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.327327,0.000000,0.000000,0.000000,0.0,0.261861
8,0.204025,0.257248,0.396911,0.138564,0.000000,0.225733,0.000000,1.000000,0.185164,0.000000,0.224781,0.196946,0.0,0.000000
9,0.000000,0.264628,0.000000,0.142539,0.000000,0.000000,0.327327,0.185164,1.000000,0.000000,0.231229,0.000000,0.0,0.000000
10,0.139131,0.140340,0.135333,0.157485,0.176483,0.123147,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.168359

In [17]:
def get_cf_wisata(user_id):

    similar_users = similarity_df[user_id]\
        .sort_values(ascending=False)[1:6]

    similar_users_index = similar_users.index

    rekomendasi = interaction[
        interaction['user_id'].isin(similar_users_index)
    ]

    rekomendasi = rekomendasi.sort_values(
        by='rating',
        ascending=False
    )

    return rekomendasi['wisata'].unique()

In [18]:
def content_based_filter(
    wisata_list,
    kategori,
    budget_min,
    budget_max,
    rating_min
):

    filtered = df[
        (df['Nama Tempat'].isin(wisata_list)) &
        (df['Kategori'].isin(kategori)) &
        (df['HTM Min Domestic'] >= budget_min) &
        (df['HTM Max Domestic'] <= budget_max) &
        (df['Rating'] >= rating_min)
    ]

    return filtered

In [19]:
def hybrid_recommendation(
    user_id,
    kategori,
    budget_min,
    budget_max,
    rating_min
):

    cf_result = get_cf_wisata(user_id)

    # # fallback jika CF sedikit
    if len(cf_result) < 5:
        cf_result = df['Nama Tempat']

    final = content_based_filter(
        cf_result,
        kategori,
        budget_min,
        budget_max,
        rating_min
    )

    final = final.sort_values(
        by='Rating',
        ascending=False
    )

    return final

In [20]:
hasil = hybrid_recommendation(
    user_id=1,
    kategori=['Wisata Alam', 'Wisata Religi', 'Wisata Edukasi'],
    budget_min=0,
    budget_max=20000,
    rating_min=4
)

print(hasil[['Nama Tempat','Kategori', 'HTM Min Domestic', 'HTM Max Domestic', 'HTM Min Mancanegara', 'HTM Max Mancanegara', 'Rating']])

                         Nama Tempat        Kategori  HTM Min Domestic  \
2                 Kebun Kopi Kemiren  Wisata Edukasi               0.0
38                    Pantai Mustika     Wisata Alam            5000.0
35                       Teluk Hijau     Wisata Alam            7500.0
49                       Pantai Boom     Wisata Alam            7500.0
24  Kebun Naga dan Jeruk Pesanggaran  Wisata Edukasi               0.0
12                      Gunung Ranti     Wisata Alam            7500.0
43                      Pantai Bedul     Wisata Alam           10000.0
98                    sendang seruni     Wisata Alam            5000.0
14               Air Terjun Legomoro     Wisata Alam               0.0
6                 Bukit Sewu Sambang     Wisata Alam            5000.0
41                     Pantai Lampon     Wisata Alam               0.0
91                     wisata japuro     Wisata Alam            5000.0
40               Pantai Parang Kursi     Wisata Alam               0.0
32               Air Terjun Legomoro     Wisata Alam            5000.0
63                   Waduk Bajulmati     Wisata Alam           10000.0
50                    Pantai Cacalan     Wisata Alam               0.0
78                 Situs Ompak Songo   Wisata Religi               0.0
25             Perkebunan Kaliklatak  Wisata Edukasi               0.0
28                     Gunung Srawet   Wisata Religi               0.0
8            Waduk Sidodadi Glenmore     Wisata Alam            3000.0
42                   Pantai Grajagan     Wisata Alam            7500.0
17         Air Terjun Selendang Arum     Wisata Alam            2000.0

    HTM Max Domestic  HTM Min Mancanegara  HTM Max Mancanegara  Rating
2                0.0                  0.0                  0.0     4.7
38            5000.0               5000.0               5000.0     4.7
35           10000.0               7500.0              10000.0     4.7
49           15000.0              10000.0              15000.0     4.7
24               0.0                  0.0                  0.0     4.6
12           10000.0               7500.0              10000.0     4.6
43           10000.0              10000.0              10000.0     4.6
98            5000.0               5000.0               5000.0     4.6
14               0.0                  0.0                  0.0     4.5
6            15000.0               5000.0              15000.0     4.5
41               0.0                  0.0                  0.0     4.5
91            5000.0               5000.0               5000.0     4.5
40               0.0                  0.0                  0.0     4.5
32            5000.0               5000.0               5000.0     4.5
63           10000.0              10000.0              10000.0     4.4
50               0.0                  0.0                  0.0     4.4
78               0.0                  0.0                  0.0     4.4
25               0.0                  0.0                  0.0     4.3
28               0.0                  0.0                  0.0     4.2
8             3000.0               3000.0               3000.0     4.2
42           15000.0               7500.0              15000.0     4.2
17            2000.0               2000.0               2000.0     4.1

In [21]:
cf_result = get_cf_wisata(2)
cf_result

<StringArray>
[             'Air Terjun Legomoro',                     'Pantai Bedul',
               'Kebun Kopi Kemiren',              'Pantai Parang Kursi',
                     'Pelangi Sari',               'Bukit Sewu Sambang',
                 'Pantai Plengkung',                      'Pulau Bedil',
                   'Pantai Mustika',                     'Muara Mbaduk',
          'Desa Adat Osing Kemiren',      'Penangkaran Banteng Baluran',
           'Kebun Kopi Gombengsari',                  'Waduk Bajulmati',
              'Air Terjun Pertemon',        'Air Terjun Telunjuk Raung',
                      'Pantai Boom',               'Pendopo Banyuwangi',
                  'Pantai Grajagan',                   'Pantai So Long',
                    'wisata japuro',                   'Pantai Cacalan',
        'Air Terjun Selendang Arum',                    'Pulau Tabuhan',
                   'sendang seruni',                  'Banyuwangi Park',
                'Pantai Wedi Ireng',          'Taman Gandrung terakota',
          'Waduk Sidodadi Glenmore',             'kali sawah adventure',
                    'Pantai Lampon', 'Kebun Naga dan Jeruk Pesanggaran',
          'Air Terjun Kedung Angin',         'pantai pancur alas purwo',
                   'Republik Osing',                'Situs Ompak Songo',
             'wisata Beji antaboga',       'Penangkaran Penyu Ngagelan']
Length: 38, dtype: str

In [ ]:
# Test simple import
print("Testing...")
import sys
print(f"Python version: {sys.version}")